export default {
   'abandoned_baby': require('./Abandoned_baby.svg'),
   'advance_block': require('./Advance_block.svg'),
   'bet_hold': require('./Bet_hold.svg'),
   'bullish piercing': require('./Bullish Piercing.svg'),
   'dark_cloud_cover': require('./Dark_cloud_cover.svg'),
   'doji': require('./Doji.svg'),
   'doji_star': require('./Doji_star.svg'),
   'download': require('./Download.svg'),
   'dragonfly_doji': require('./Dragonfly_doji.svg'),
   'engulfing_pattern': require('./Engulfing_pattern.svg'),
   'inverted-hammer': require('./Inverted-hammer.svg'),
   'breakaway_pattern': require('./breakaway_pattern.svg'),
   'closing_marubozu': require('./closing_marubozu.svg'),
   'counterattack': require('./counterattack.svg'),
   'down_fractal': require('./down_fractal.svg'),
   'evening_doji_star': require('./evening_doji_star.svg'),
   'evening_star': require('./evening_star.svg'),
   'gap_three_methods': require('./gap_three_methods.svg'),
   'gravestone_doji': require('./gravestone_doji.svg'),
   'hammer': require('./hammer.svg'),
   'hanging_man': require('./hanging_man.svg'),
   'harami_cross': require('./harami_cross.svg'),
   'harami_pattern': require('./harami_pattern.svg'),
   'high_wave': require('./high_wave.svg'),
   'hikkake': require('./hikkake.svg'),
   'homing_pigeon': require('./homing_pigeon.svg'),
   'identical_three_crows': require('./identical_three_crows.svg'),
   'in-neck': require('./in-neck.svg'),
   'kicking': require('./kicking.svg'),
   'ladder-bottom': require('./ladder-bottom.svg'),
   'long-legged-doji': require('./long-legged-doji.svg'),
   'long-line-candles': require('./long-line-candles.svg'),
   'marubozu': require('./marubozu.svg'),
   'mat-hold': require('./mat-hold.svg'),
   'matching-low': require('./matching-low.svg'),
   'morning-doji-start': require('./morning-doji-start.svg'),
   'morning-star': require('./morning-star.svg'),
   'on-neck': require('./on-neck.svg'),
   'rickshaw man': require('./rickshaw man.svg'),
   'rising falling three methods': require('./rising falling three methods.svg'),
   'salled pattern': require('./salled pattern.svg'),
   'separating lines': require('./separating lines.svg'),
   'shooting star': require('./shooting star.svg'),
   'short line candle': require('./short line candle.svg'),
   'side by side white line': require('./side by side white line.svg'),
   'spinning top': require('./spinning top.svg'),
   'stick sandwich 2': require('./stick sandwich 2.svg'),
   'stick sandwich': require('./stick sandwich.svg'),
   'takuri line': require('./takuri line.svg'),
   'tasuki gap': require('./tasuki gap.svg'),
   'three_black_crows': require('./three_black_crows.svg'),
   'three_line_strike': require('./three_line_strike.svg'),
   'three_outside_up_down': require('./three_outside_up_down.svg'),
   'three_river': require('./three_river.svg'),
   'three_stars_in_the_south': require('./three_stars_in_the_south.svg'),
   'three_white_soldiers': require('./three_white_soldiers.svg'),
   'thrusting_pattern': require('./thrusting_pattern.svg'),
   'tristar': require('./tristar.svg'),
   'two_crows': require('./two_crows.svg'),
   'typprice': require('./typprice.svg'),
   'up_fractal': require('./up_fractal.svg'),
   'upside_gap_two_crows': require('./upside_gap_two_crows.svg'),
};
